site_name: CELL SPOTTER (CSPOT)
site_description: A scalable framework for automated processing of highly multiplexed tissue images
site_author: Ajit Johnson Nirmal
docs_dir: docs/

repo_url: https://github.com/nirmalLab/cspot/
edit_uri: https://github.com/nirmalLab/cspot/edit/main/docs

theme:
  name: material
  logo: ./assets/favicon.png
  favicon: ./assets/favicon.png
  features:
    - navigation.instant
  features:
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


nav:
    - Home: 'index.md'
    - Getting Started: 'Getting Started.md'
    - CSPOT Functions:
        - Build CSPOT Model:
            - generateThumbnails: 'Functions/generateThumbnails.md'
            - cloneFolder: 'Functions/cloneFolder.md'
            - generateTrainTestSplit: 'Functions/generateTrainTestSplit.md'
            - csTrain: 'Functions/csTrain.md'
        - Run CSPOT Algorithm:
            - csPipeline: 'Functions/csPipeline.md'
            - csPredict: 'Functions/csPredict.md'
            - generateCSScore: 'Functions/generateCSScore.md'
            - csObject: 'Functions/csObject.md'
            - cspot: 'Functions/cspot.md'
            - mergecsObject: 'Functions/mergecsObject.md'
        - Phenotype cells:
            - csPhenotype: 'Functions/csPhenotype.md'
        - Helper Functions:
            - csExport: 'Functions/csExport.md'
            - scatterPlot: 'Functions/scatterPlot.md'
            - addPredictions: 'Functions/addPredictions.md'
    - Tutorials:
        - Review Quick Start Guide: 'Tutorials/md/ReviewQuickStartGuide.md'
        - Download Tutorial Data: 'Tutorials/md/DownloadTutorialData.md'
        - Installation and Set Up: 'Tutorials/md/InstallationandSetUp.md'
        - Build CSPOT Model: 'Tutorials/md/BuildCSPOTModel.md'
        - Run CSPOT Algorithm: 'Tutorials/md/RunCSPOTAlgorithm.md'
        - Phenotype Cells: 'Tutorials/md/PhenotypeCells.md'
        - Helper Functions: 'Tutorials/md/HelperFunctions.md'
        - Run CSPOT with Docker: 'Tutorials/md/RunCSPOTwithDocker.md'


plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_signature_annotations: no
          heading_level: 4

extra_css:
  - stylesheets/extra.css


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2024 | Nirmal Lab | www.nirmallab.com

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nirmallab
      name: Twitter